default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  schema_search_path: public

development:
  <<: *default
  host: db
  username: postgres
  password:
  database: rails-batch-sample_development

test:
  <<: *default
  host: db
  username: postgres
  password:
  database: rails-batch-sample_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
